### ISSUE TITLE
Unable to backup when snapshot exists

### ISSUE THREAD

**Issue by diver-ua** [abbbi/qmpbackup#12]
Hello.
Currently, when there is backing file + file, the backup for this device does not work.
```
json:{"backing": {"driver": "qcow2", "file": {"driver": "file", "filename": "/hdd/OC.qcow2"}}, "driver": "qcow2", "file": {"driver": "file", "filename": "/var/tmp/vl.RUCII2"}} (qcow2)
```
So,  for backup automation, would be very useful option like "--auto-commit" or something.

Currently, backup status should be monitored, and commits performed manualy (via qmp-shell), if scheduled backup failed because of such situation.

**Comment by abbbi** [comment]
while implementing i was not quite sure how snapshots (backing devices) interact with dirty bitmaps, so i have built in a check to disable backup (its better to warn the user directly instead of backing up only half the data). More information on how to handle them is required.

**Comment by abbbi** [comment]
i did a quick test and changed the CI script to use a disk with backing image and the tests succeeded, apparently all data was backed up correctly. Can you confirm? Changes to allow for backup with active backing devices in branch "12":

https://github.com/abbbi/qmpbackup/tree/12

**Comment by diver-ua** [comment]
It's attempts to perform backup, but with hidden snapshots there is another error:

![image](https://github.com/abbbi/qmpbackup/assets/58228615/fe447d71-796e-47b8-b36b-2c919fb103df)

**Comment by abbbi** [comment]
the problem seems to be that the function trying to get the qemu image information fails to parse the qemu-img ouptut if backing file is existant. How is the "temporary" snapshot created and why is the file not existant anymore?

**Comment by diver-ua** [comment]
the snapshot was created by passing parameter `snapshot=on` for the drive to qemu command line:
```
-drive id=OpenCoreBoot,if=none,format=qcow2,snapshot=on,file=/hdd/OC.qcow2,
```

In this case, qemu creates "temporary" snapshot file, and deletes it immediately. While file descriptor is active, file's body remains active and accessible, serving in's purposes. And, if qemu is stopped/killed - it silently disappear. Therefore, the snapshot file exists only for "qemu" process, accessible by descriptor and not accessible for any external utilities...

By using qmp commands ` block-commit device=<...>` and (after job finish) `block-job-complete device=<...>`, contents of snapshot are committed into backing image, and backup is working...

**Comment by abbbi** [comment]
the problem is not about the backing file layer but that qmpbackup attempts to call qemu-img to get the image information. The snapshot file is not found and it bails out, please check with commit:

https://github.com/abbbi/qmpbackup/commit/46464390f902ee2e40f348d847d59aff6fc267e5

**Comment by abbbi** [comment]
https://github.com/abbbi/qmpbackup/commit/8af9420ce46cd8969faa29d4df2003bd1b4b5163

**Comment by diver-ua** [comment]
Unfortunately, I deleted backup dir, and now getting another errors...
Will try to cleanup everything (bitmaps, etc), and try to continue, but it will be a bit later - in few hours or tomorrow (have to commute...)

```
/usr/local/bin/qmpbackup:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('qmpbackup==0.29', 'qmpbackup')
[2024-02-13 16:08:09,625]    INFO  Version: 0.29 Arguments: /usr/local/bin/qmpbackup --socket /run/qemu/qmp.sock --agent-socket /var/run/qemu/guest-agent.sock backup --target /hdd/backup --quiesce --level auto
[2024-02-13 16:08:09,626]    INFO  Connecting QMP socket: [/run/qemu/qmp.sock]
[2024-02-13 16:08:09,630]    INFO  VM is in state: [running]
[2024-02-13 16:08:09,630]    INFO  Qemu version: [8.1.2] [Debian 1:8.2.1+ds-1]
[2024-02-13 16:08:09,634] WARNING  Excluding device with raw format from backup: [pflash0:OVMF_CODE_4M.fd]
[2024-02-13 16:08:09,634] WARNING  Excluding device with raw format from backup: [pflash1:OVMF_VARS.fd]
[2024-02-13 16:08:09,635]    INFO  Active backing image for disk "OpenCoreBoot"
[2024-02-13 16:08:09,635]   ERROR  Bitmap exists, but target directory does not contain full backup.
```

```
/usr/local/bin/qmpbackup:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('qmpbackup==0.29', 'qmpbackup')
[2024-02-13 16:12:25,241]    INFO  Version: 0.29 Arguments: /usr/local/bin/qmpbackup --socket /run/qemu/qmp.sock --agent-socket /var/run/qemu/guest-agent.sock backup --target /hdd/backup --quiesce --level full
[2024-02-13 16:12:25,241]    INFO  Connecting QMP socket: [/run/qemu/qmp.sock]
[2024-02-13 16:12:25,244]    INFO  VM is in state: [running]
[2024-02-13 16:12:25,245]    INFO  Qemu version: [8.1.2] [Debian 1:8.2.1+ds-1]
[2024-02-13 16:12:25,249] WARNING  Excluding device with raw format from backup: [pflash0:OVMF_CODE_4M.fd]
[2024-02-13 16:12:25,249] WARNING  Excluding device with raw format from backup: [pflash1:OVMF_VARS.fd]
[2024-02-13 16:12:25,249]    INFO  Active backing image for disk "OpenCoreBoot"
[2024-02-13 16:12:25,250]    INFO  Backup target directory: /hdd/backup
[2024-02-13 16:12:25,250] WARNING  Unable to save image file info: not existent: skipping: [json:{"backing": {"driver": "qcow2", "file": {"driver": "file", "filename": "/hdd/OC.qcow2"}}, "driver": "qcow2", "file": {"driver": "file", "filename": "/var/tmp/vl.KLRXI2"}}]
[2024-02-13 16:12:25,266]    INFO  Saved image info: [/hdd/backup/HDD0.config]
Traceback (most recent call last):
  File "/usr/local/bin/qmpbackup", line 4, in <module>
    __import__('pkg_resources').run_script('qmpbackup==0.29', 'qmpbackup')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1572, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.11/dist-packages/qmpbackup-0.29-py3.11.egg/EGG-INFO/scripts/qmpbackup", line 391, in <module>
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/qmpbackup-0.29-py3.11.egg/EGG-INFO/scripts/qmpbackup", line 342, in main
  File "/usr/local/lib/python3.11/dist-packages/qmpbackup-0.29-py3.11.egg/libqmpbackup/image.py", line 102, in create
  File "/usr/local/lib/python3.11/dist-packages/qmpbackup-0.29-py3.11.egg/libqmpbackup/image.py", line 62, in _get_options_cmd
FileNotFoundError: [Errno 2] No such file or directory: '/hdd/backup/OpenCoreBoot.config'
```

**Comment by diver-ua** [comment]
It silently skipped.

```
usr/local/bin/qmpbackup:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('qmpbackup==0.29', 'qmpbackup')
[2024-02-13 16:23:23,100]    INFO  Version: 0.29 Arguments: /usr/local/bin/qmpbackup --socket /run/qemu/qmp.sock --agent-socket /var/run/qemu/guest-agent.sock backup --target /hdd/backup --quiesce --level full
[2024-02-13 16:23:23,100]    INFO  Connecting QMP socket: [/run/qemu/qmp.sock]
[2024-02-13 16:23:23,105]    INFO  VM is in state: [running]
[2024-02-13 16:23:23,105]    INFO  Qemu version: [8.1.2] [Debian 1:8.2.1+ds-1]
[2024-02-13 16:23:23,110] WARNING  Excluding device with raw format from backup: [pflash0:OVMF_CODE_4M.fd]
[2024-02-13 16:23:23,110] WARNING  Excluding device with raw format from backup: [pflash1:OVMF_VARS.fd]
[2024-02-13 16:23:23,112]    INFO  Backup target directory: /hdd/backup
[2024-02-13 16:23:23,133]    INFO  Saved image info: [/hdd/backup/HDD0.config]
[2024-02-13 16:23:23,134]    INFO  Create target backup image: [/hdd/backup/HDD0//FULL-1707841403-HDD0.qcow2.partial], virtual size: [162135015424]
[2024-02-13 16:23:23,166]    INFO  Guest Agent socket connected
[2024-02-13 16:23:23,166]    INFO  Trying to ping guest agent
[2024-02-13 16:23:28,171] WARNING  Unable to reach Guest Agent: can't freeze file systems.
[2024-02-13 16:23:28,171]    INFO  Prepare backup target devices
[2024-02-13 16:23:28,175]    INFO  Creating new bitmap: [qmpbackup-HDD0] for device [HDD0]
[2024-02-13 16:23:28,212]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 0% (2752512 of 162135015424)
[2024-02-13 16:23:29,214]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 0% (498008064 of 162135015424)
[2024-02-13 16:23:30,215]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 1% (836370432 of 162135015424)
[2024-02-13 16:23:31,256]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 1% (1265893376 of 162135015424)
[2024-02-13 16:23:32,407]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 1% (1519779840 of 162135015424)
...
...
...
[2024-02-13 16:27:19,156]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 99% (160977780736 of 162135015424)
[2024-02-13 16:27:20,336]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 100% (161938931712 of 162135015424)
[2024-02-13 16:27:21,345]    INFO  Saved all disks
[2024-02-13 16:27:21,345]    INFO  Cleanup added backup target devices
[2024-02-13 16:27:21,347] WARNING  Unable to cleanup: Failed to find node with node-name='qmpbackup-OpenCoreBoot'
[2024-02-13 16:27:21,348]    INFO  Renaming partial files
```

**Comment by abbbi** [comment]
Yes i think that would be Desired behavior? WhatsApp Data would be in the Snapshot anyway?

**Comment by diver-ua** [comment]
When backup started in incremental mode - agreed.
When backup started in full mode - this behavior is questionable, because "full" backup will not be full.

As for myself - I will run qmp-shell command `query-block` to determine, if there are devices with volatile snapshots, and perform "commit" action.

Thank you for your creation - it simplifies everything a lot.

**Comment by abbbi** [comment]
can you re-check with latest commit? It should now backup backing images, too:

```
[2024-02-13 21:16:52,591]    INFO  Clearing existing bitmap for device: [ide0-hd0]
[2024-02-13 21:16:52,591]    INFO  Clearing existing bitmap for device: [ide0-hd1]
[2024-02-13 21:16:52,591]    INFO  Clearing existing bitmap for device: [snapshot]
[2024-02-13 21:16:52,595]    INFO  [ide0-hd0:disk1.qcow2] Wrote Offset: 0% (0 of 137438953472)
[2024-02-13 21:16:52,595]    INFO  [ide0-hd1:disk2.qcow2] Wrote Offset: 0% (0 of 10485760)
[2024-02-13 21:16:52,595]    INFO  [snapshot:snapshot.qcow2] Wrote Offset: 0% (0 of 10485760)
[2024-02-13 21:16:53,597]    INFO  [ide0-hd0:disk1.qcow2] Wrote Offset: 80% (110058471424 of 137438953472)

```

**Comment by diver-ua** [comment]
Unfortunately, it's failed.
```
/usr/local/bin/qmpbackup:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('qmpbackup==0.29', 'qmpbackup')
[2024-02-13 22:46:42,327]    INFO  Version: 0.29 Arguments: /usr/local/bin/qmpbackup --socket /run/qemu/qmp.sock --agent-socket /var/run/qemu/guest-agent.sock backup --target /hdd/backup --quiesce --level full
[2024-02-13 22:46:42,327]    INFO  Connecting QMP socket: [/run/qemu/qmp.sock]
[2024-02-13 22:46:42,331]    INFO  VM is in state: [running]
[2024-02-13 22:46:42,331]    INFO  Qemu version: [8.1.2] [Debian 1:8.2.1+ds-1]
[2024-02-13 22:46:42,333] WARNING  Excluding device with raw format from backup: [pflash0:OVMF_CODE_4M.fd]
[2024-02-13 22:46:42,334] WARNING  Excluding device with raw format from backup: [pflash1:OVMF_VARS.fd]
[2024-02-13 22:46:42,334]    INFO  Active backing image for disk "OpenCoreBoot"
[2024-02-13 22:46:42,334]    INFO  Backup target directory: /hdd/backup
[2024-02-13 22:46:42,334] WARNING  Unable to save image file info: not existent: skipping: [json:{"backing": {"driver": "qcow2", "file": {"driver": "file", "filename": "/hdd/OC.qcow2"}}, "driver": "qcow2", "file": {"driver": "file", "filename": "/var/tmp/vl.SZDRI2"}}]
[2024-02-13 22:46:42,350]    INFO  Saved image info: [/hdd/backup/HDD0.config]
Traceback (most recent call last):
  File "/usr/local/bin/qmpbackup", line 4, in <module>
    __import__('pkg_resources').run_script('qmpbackup==0.29', 'qmpbackup')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 722, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1572, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/local/lib/python3.11/dist-packages/qmpbackup-0.29-py3.11.egg/EGG-INFO/scripts/qmpbackup", line 391, in <module>
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/qmpbackup-0.29-py3.11.egg/EGG-INFO/scripts/qmpbackup", line 342, in main
  File "/usr/local/lib/python3.11/dist-packages/qmpbackup-0.29-py3.11.egg/libqmpbackup/image.py", line 102, in create
  File "/usr/local/lib/python3.11/dist-packages/qmpbackup-0.29-py3.11.egg/libqmpbackup/image.py", line 62, in _get_options_cmd
FileNotFoundError: [Errno 2] No such file or directory: '/hdd/backup/OpenCoreBoot.config'
```

**Comment by abbbi** [comment]
are you sure you are using the right branch?
IM testing with the following qemu command line and it works just nicely.

```
~/qmpbackup (12)$ git branch
* 12
qemu-system-x86_64 -name testvm --enable-kvm -smp 16 -daemonize -display none -m 1024 -hda /tmp/disk1.qcow2 -hdb /tmp/disk2.qcow2 -hdc /tmp/disk3.raw -qmp unix:/tmp/socket,server=on,wait=off -chardev socket,path=/tmp/qga.sock,server=on,wait=off,id=qga0 -device virtio-serial -device virtserialport,chardev=qga0,name=org.qemu.guest_agent.0 -drive id=snapshot,if=none,format=qcow2,snapshot=on,file=/tmp/snapshot.qcow2 -pidfile /tmp/qemu.pid
```

**Comment by diver-ua** [comment]
output of `git branch -v`:
```
* 12 222c413 cleanup
```

It builds with docker, build cache disabled.

I just re-run the ci pipeline, and  tried again.
```
[2024-02-14 08:42:16,893]    INFO  Version: 0.29 Arguments: /usr/local/bin/qmpbackup --socket /run/qemu/qmp.sock --agent-socket /var/run/qemu/guest-agent.sock backup --target /hdd/backup --quiesce --level full
[2024-02-14 08:42:16,894]    INFO  Connecting QMP socket: [/run/qemu/qmp.sock]
[2024-02-14 08:42:16,897]    INFO  VM is in state: [running]
[2024-02-14 08:42:16,897]    INFO  Qemu version: [8.1.2] [Debian 1:8.2.1+ds-1]
[2024-02-14 08:42:16,900] WARNING  Excluding device with raw format from backup: [pflash0:OVMF_CODE_4M.fd]
[2024-02-14 08:42:16,900] WARNING  Excluding device with raw format from backup: [pflash1:OVMF_VARS.fd]
[2024-02-14 08:42:16,900]    INFO  Backup target directory: /hdd/backup
[2024-02-14 08:42:16,915]    INFO  Saved image info: [/hdd/backup/OpenCoreBoot.config]
[2024-02-14 08:42:16,930]    INFO  Saved image info: [/hdd/backup/HDD0.config]
[2024-02-14 08:42:16,930]    INFO  Create target backup image: [/hdd/backup/OpenCoreBoot//FULL-1707900136-OC.qcow2.partial], virtual size: [209715200]
[2024-02-14 08:42:16,952]    INFO  Create target backup image: [/hdd/backup/HDD0//FULL-1707900136-HDD0.qcow2.partial], virtual size: [162135015424]
[2024-02-14 08:42:16,971]    INFO  Guest Agent socket connected
[2024-02-14 08:42:16,971]    INFO  Trying to ping guest agent
[2024-02-14 08:42:21,975] WARNING  Unable to reach Guest Agent: can't freeze file systems.
[2024-02-14 08:42:21,976]    INFO  Prepare backup target devices
[2024-02-14 08:42:21,987]    INFO  Creating new bitmap: [qmpbackup-OpenCoreBoot] for device [OpenCoreBoot]
[2024-02-14 08:42:21,987]    INFO  Creating new bitmap: [qmpbackup-HDD0] for device [HDD0]
[2024-02-14 08:42:22,075]    INFO  [OpenCoreBoot:OC.qcow2] Wrote Offset: 0% (0 of 209715200)
[2024-02-14 08:42:22,075]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 0% (5963776 of 162135015424)
...
...
[2024-02-14 08:45:40,690]    INFO  [HDD0:HDD0.qcow2] Wrote Offset: 100% (162008203264 of 162135015424)
[2024-02-14 08:45:41,701]    INFO  Saved all disks
[2024-02-14 08:45:41,701]    INFO  Cleanup added backup target devices
[2024-02-14 08:45:41,963]    INFO  Renaming partial files
```

Thank you!

**Comment by abbbi** [comment]
thanks, merged to master
